version: '3'
services:

  erdcloud-message:
    image: openjdk:8
    container_name: ${rootArtifactId}
    #restart: always
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 512M
    volumes:
      - ../apps:/deployments
      - ../logs:/logs
    entrypoint: java -Xms512m -Xmx1024m -jar -server -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom /deployments/${rootArtifactId}-$APP_VERSION.jar
    ports:
      - '7003:7003'
networks:
  default:
    external:
      name: erdc-bridge