info:
  group: '@project.groupId@'
  artifactId: '@project.artifactId@'
  version: '@project.version@'
  description: '@project.description@'
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration